services:

  # Dashboard
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    network_mode: host
    volumes:
      - /srv/glance:/app/config
      - /srv/glance/assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock

  # Webapp htop
  monitoring:
    container_name: monitoring
    image: nicolargo/glances:latest-full
    pid: host
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock
    environment:
      - "GLANCES_OPT=-w"
    restart: unless-stopped

  # HA
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /srv/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"

  # Might bring back when doing assistant
  #whisper-stt:
  #  image: rhasspy/wyoming-whisper
  #  container_name: whisper-stt
  #  command: --model base --language pl
  #  ports:
  #    - "10300:10300"
  #  restart: unless-stopped
  #  networks:
  #    - homeassistant

  # Might bring back when Sendspin comes out of beta
  #music-assistant-server:
  #  image: ghcr.io/music-assistant/server:nightly # <<< Desired release version here (or use beta to get the latest beta version)
  #  container_name: music-assistant-server
  #  restart: unless-stopped
  #   # Network mode must be set to host for MA to work correctly
  #  network_mode: host
  #  volumes:
  #     - /srv/music-assistant-server/data:/data/
  #  # privileged caps (and security-opt) needed to mount smb folders within the container
  #  cap_add:
  #    - SYS_ADMIN
  #    - DAC_READ_SEARCH
  #  security_opt:
  #     - apparmor:unconfined
  #  environment:
  #    # Provide logging level as environment variable.
  #    # default=info, possible=(critical, error, warning, info, debug)
  #     - LOG_LEVEL=info

  # Used for custom integrations
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /srv/mosquitto/config:/mosquitto/config
      - /srv/mosquitto/data:/mosquitto/data
      - /srv/mosquitto/log:/mosquitto/log
    environment:
      - TZ=Europe/Warsaw
    networks:
      - homeassistant

  # Govee bulbs
  pv2mqtt:
    image: ghcr.io/wez/govee2mqtt:latest
    container_name: govee2mqtt
    restart: unless-stopped
    env_file:
      - .env
    network_mode: host

  # Private alternative to cloudflared
  # tailscale:
  #   container_name: ts_homeassistant
  #   image: tailscale/tailscale:latest
  #   restart: unless-stopped
  #   cap_add:
  #     - NET_ADMIN
  #     - NET_RAW
  #   volumes:
  #     - /dev/net/tun:/dev/net/tun
  #     - /srv/tailscale/varlib:/var/lib
  #     - /srv/tailscale/tmp:/tmp
  #     - /srv/tailscale/tls:/var/lib/tailscale/certs
  #   environment:
  #     - TS_STATE_DIR=/var/lib/tailscale
  #     - TS_HOSTNAME=ha
  #     - TS_DEST_IP=192.168.0.10
  #     - TS_USERSPACE=0
  #   network_mode: host

  # Setup for public access
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run homelab-tunnel
    environment:
      - TUNNEL_ORIGIN_CERT=/etc/cloudflared/cert.pem
    volumes:
      - /srv/cloudflare:/etc/cloudflared
    network_mode: host

  # File server
  samba:
    container_name: samba
    image: dperson/samba:latest
    restart: unless-stopped
    ports:
      - "139:139"
      - "445:445"
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - /srv/samba:/mount
    command: >
      -u "test;test"
      -s "shared;/mount/shared;yes;no;no;test"

  # For quick development
  vscode:
    container_name: vscode
    image: codercom/code-server:4.96.4
    volumes:
      - /srv:/home/coder/project:rw
      - /srv/vscode:/home/coder/.local/share/code-server:rw
    ports:
      - "8443:8080"
    command: code-server --auth password --disable-telemetry /home/coder/project
    environment:
      PASSWORD: "${VSCODE_PASSWORD}"
    user: "${LOCAL_USER}:${LOCAL_USER}"
    restart: unless-stopped

  # Everything presence sensors and tinkering
  esphome:
    container_name: ephome
    image: esphome/esphome
    volumes:
      - /srv/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host

  # External automations for HA
  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Warsaw
    ports:
      - "1880:1880"
    volumes:
      - /srv/node-red:/data
    restart: unless-stopped

  # Another hosted service
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: always
    ports:
      - "9925:9000"
    volumes:
      - /srv/mealie:/app/data
    environment:
      ALLOW_SIGNUP: "true"
      TZ: "Europe/Warsaw"
      DEFAULT_EMAIL: "test"
      DEFAULT_PASSWORD: "test"

networks:
  homeassistant:
    driver: bridge
